resources:
- repo: self
  clean: true
trigger:
  batch: true
  branches:
    include:
    - master
schedules:
- cron: "0 17 * * Fri"
  always: true
  displayName: Weekly build
  branches:
    include:
    - master
pool:
  vmImage: 'windows-latest'
variables:
  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- checkout: self
  submodules: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName : Build
  inputs:
    projects: '**/*.csproj'
    arguments: '-c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'BulkDeviceCreator/BulkDeviceCreator.csproj'
    arguments: '--no-build -c $(BuildConfiguration) -o $(build.artifactstagingdirectory)'
    zipAfterPublish: false
    modifyOutputPath: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'IoTClient.Cli/IoTClient.Cli.csproj'
    arguments: '--no-build -c $(BuildConfiguration) -o $(build.artifactstagingdirectory)'
    zipAfterPublish: false
    modifyOutputPath: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'IoTDeviceManager/IoTDeviceManager.csproj'
    arguments: '--no-build -c $(BuildConfiguration) -o $(build.artifactstagingdirectory)'
    zipAfterPublish: false
    modifyOutputPath: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: 'IoTDeviceManager'
    targetPath: '$(build.artifactstagingdirectory)'
